export const palestrantes = [
  {
    "id": 1,
    "name": "FRANCISCO SOUSA - GERENTE NA ACCENTURE BRASIL",
    "avatar": "img/peoples/francisco.sousa.png",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Perspectivas para mercado de TI na Paraíba e habilidades mais importantes para construir uma carreira.",
  },
  {
    "id": 2,
    "name": "WESLEY P. SANTOS - ADMINISTRADOR DE REDES NA UEPB",
    "avatar": "img/peoples/wesley.porto.png",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Boas práticas de rede com Mikrotik / RouterOS",
  },
  {
    "id": 3,
    "name": "IVOMAR B. SOARES - SOFTWARE ENGINEER NA MICROSOFT",
    "avatar": "img/peoples/ivomar.soares.jpeg",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Experiências de trabalho remoto de engenheiro de software para Microsfot.",
  },
  {
    "id": 4,
    "name": "JOÃO MARCONDES- TÉCNICO EM ELETROTÉCNICA",
    "avatar": "img/peoples/energia.solar.jpeg",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Zon Energia Solar - Empresa Pioneira de Energia Solar do Curimataú Paraibano",
  },
  {
    "id": 5,
    "name": "RENATA KELLY- SISTEMAS DE INFORMAÇÃO (UFRN)",
    "avatar": "img/peoples/renata.kelly.jpeg",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Comunidade Potiguaras Valley, <b>@TI&ltfor&gtGIRLS</b> e desenvolvedora mobile.",
  },
  {
    "id": 6,
    "name": "EDMILSON ZACARIAS - EGRESSO DO IFPB CAMPUS PICUÍ",
    "avatar": "img/peoples/edmilson.zacarias.png",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Mesa Redonda com ex-alunos do curso de Informática",
  },
  {
    "id": 7,
    "name": "ALVARO GETÚLIO - EGRESSO DO IFPB CAMPUS PICUÍ",
    "avatar": "img/peoples/alvaro.getulio.png",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": "https://github.com/",
    "frase": "Mesa Redonda com ex-alunos do curso de Informática",
  },
  {
    "id": 8,
    "name": "ALEXSANDRA MACEDO - EGRESSA DO IFPB CAMPUS PICUÍ",
    "avatar": "img/peoples/alexsandra.macedo.png",
    "instagram": "/",
    "email": null,
    "linkedinIn": "/",
    "github": null,
    "frase": "Mesa Redonda com ex-alunos do curso de Informática",
  }
]